### ISSUE TITLE
docker-compose 3.4 support

### ISSUE THREAD

**Issue by blaggacao** [citusdata/docker#69] opened 2018-01-26 17:08 UTC
The `depends_on` flag was conceptually simplified only  representing "docker running"
Readiness testing was made responsibility of the application.

**Comment by blaggacao** [comment] 2018-01-26 17:12
see: https://docs.docker.com/compose/startup-order/

**Comment by vinhbuivan** [comment] 2019-10-30 21:48
Checkout with this docker-compose version. I tested and it run on docker stack.
`
version: '3.7'
services:
  master:    
    image: 'citusdata/citus:8.3.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master', 'com.docker.compose.project=citus']
    healthcheck:
  worker:
    image: 'citusdata/citus:8.3.2'
    labels: ['com.citusdata.role=Worker', 'com.docker.compose.project=citus']
    depends_on: manager      
  manager:    
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
	labels: ['com.citusdata.role=Manager', 'com.docker.compose.project=citus']
    depends_on: master      
`

**Comment by mubaidr** [comment] 2020-04-07 09:02
Issue [#124 Worker node not being added](https://github.com/citusdata/docker/issues/124) is caused by this. Because manager service tries to connect to master service before it is ready and fails. But setting it to restart: on-failure will make sure it tires multiple times and eventually it will work. 

More info: https://github.com/citusdata/docker/issues/124#issuecomment-610234165

**Comment by hanefi** [comment] 2020-04-13 09:03
I created two PRs that aims to resolve this issue:
1. https://github.com/citusdata/membership-manager/pull/9 implements a polling mechanism in Membership Manager, so that (a) it will detect the readiness of the coordinator node, (b) properly report that it is ready to accept new Citus worker services
2. https://github.com/citusdata/docker/pull/187 (a) updates the docker images to properly detect dependencies, (b) introduce Compose V3 definitions

Once they are merged, this issue should be resolved

**Closed** 2020-12-08 14:53 UTC
